name: Release

on: push 

env:
  COSIGN_EXPERIMENTAL: 1

jobs: 
  sign:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      id-token: write, read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install in-toto
        run: |
          pip install in-toto
          in-toto-sign --version

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.1.0
        with:
          cosign-release: v1.6.0

      - name: Print Cosign version
        run: |
          cosign version

      - name: Generate keypair
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          cargo r --bin keygen ${{ secrets.GITHUB_TOKEN }}
          #ls -l cosign.key cosign.pub
