name: SSCS

on: push 

env:
  COSIGN_EXPERIMENTAL: 1

permissions:
  id-token: write

jobs: 
  sign:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install in-toto
        run: |
          pip install in-toto
          in-toto-sign --version

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.1.0
        with:
          cosign-release: v1.6.0

      - name: Print Cosign version
        run: |
          cosign version

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Generate keypair
        run: |
          ls -l
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq '.value' | tr '"' ' ')
          cargo r --bin keygen $OIDC_TOKEN
          ls -l
