name: Release

on: push 

env:
  COSIGN_EXPERIMENTAL: 1

jobs: 
  build: 
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Build
        run: cargo b --verbose

      - name: Test
        run: cargo t --verbose -- --show-output

  sign:
    runs-on: ubuntu-20.04
    needs: [build]
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.1.0
        with:
          cosign-release: v1.6.0
      - name: Print Cosign version
        run: |
          cosign version
