name: Release

on: push 

env:
  COSIGN_EXPERIMENTAL: 1

permissions:
  id-token: write
  issues: write

jobs: 
  sign:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install in-toto
        run: |
          pip install in-toto
          in-toto-sign --version

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.1.0
        with:
          cosign-release: v1.6.0

      - name: Print Cosign version
        run: |
          cosign version

      - name: Login to ghcr.io
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate keypair
        run: |
          echo "token: ${{ github.token }}"
          cargo r --bin keygen ${{ github.token }}
          #ls -l cosign.key cosign.pub
